blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/KevinBatdorf/alpine-inline-devtools/issues/new
    about: Submit a GitHub issue
  # - name: Feature Request
  #   url: https://github.com/KevinBatdorf/alpine-inline-devtools/discussions/new
  #   about: Request a feature to be added to the platform
  # - name: Ask a Question
  #   url: https://github.com/KevinBatdorf/alpine-inline-devtools/discussions/new
  #   about: Ask questions and discuss with other community members
